services:
  web:
    build: .
    container_name: django_app
    command: poetry run python server/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      # Настроим переменные окружения для Django. Например:
      DJANGO_SETTINGS_MODULE: "myproject.settings"
      # Если ваш settings.py берет параметры БД из переменных:
      MONGO_HOST: "mongo"
      MONGO_PORT: "27017"
    # Можно добавить restart: unless-stopped для перезапуска

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

volumes:
  mongo_data:
