# Generated by Django 3.1.12 on 2024-12-09 21:27

from django.db import migrations, models
import djongo.models.fields
import form_templates.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fields', djongo.models.fields.ArrayField(model_container=form_templates.models.FormField)),
            ],
        ),
    ]
